# Generated by Django 2.1.2 on 2018-11-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0002_auto_20181102_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='password',
        ),
    ]
