# Generated by Django 2.1.2 on 2018-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0003_auto_20181102_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
