# Generated by Django 2.1.2 on 2018-11-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0005_auto_20181106_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('action_type', models.CharField(max_length=64)),
                ('action_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=64)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('param', models.CharField(blank=True, max_length=512, null=True)),
                ('result', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
