# Generated by Django 2.1.2 on 2018-11-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0006_operatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='wadmin.Role'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wadmin.Permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='wadmin.Permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='sql_permissions',
            field=models.ManyToManyField(blank=True, null=True, to='wadmin.SQLPermission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='wadmin.Role'),
        ),
    ]
