# Generated by Django 2.1.2 on 2018-11-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0008_auto_20181106_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginstatus',
            name='active_time',
            field=models.IntegerField(default=30),
        ),
    ]
