# Generated by Django 2.1.2 on 2018-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0009_auto_20181106_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='alias_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='companys',
            field=models.ManyToManyField(blank=True, null=True, to='wadmin.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='sqlpermission',
            name='sql_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
