# Generated by Django 2.1.2 on 2018-11-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0011_auto_20181107_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
