# Generated by Django 2.1.2 on 2018-11-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0012_auto_20181108_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enabled',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='permission',
            name='enabled',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='role',
            name='enabled',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sqlpermission',
            name='enabled',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.IntegerField(default=1),
        ),
    ]
