# Generated by Django 2.1.2 on 2018-11-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0013_auto_20181108_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Resource',
        ),
        migrations.RenameModel(
            old_name='SQLPermission',
            new_name='SQLResource',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='permissions',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='sql_permissions',
            new_name='sql_resources',
        ),
    ]
