# Generated by Django 2.1.2 on 2018-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0014_auto_20181109_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlresource',
            name='sql_desc',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
