# Generated by Django 2.1.2 on 2018-11-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0015_sqlresource_sql_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlresource',
            old_name='sql_desc',
            new_name='sql_script',
        ),
    ]
